version: "3"
services:
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
